name: Feature request
description: Suggest an idea for TransitOS
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What problem does this solve? What are you trying to do that you currently can't?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Your proposed solution
      description: What would you like TransitOS to do instead?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
